apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-modelo-deployment
spec:
  template:
    metadata:
      name: api-modelo-pod
      labels:
        app: api-modelo-pod
    spec:
      containers:
        - name: api-modelo-container
          image: luanpaivadev/api-modelo:latest
          envFrom:
            - configMapRef:
                name: api-modelo-configmap
  replicas: 2
  selector:
    matchLabels:
      app: api-modelo-pod