apiVersion: v1
kind: Service
metadata:
  name: svc-api-modelo
spec:
  type: NodePort
  selector:
    app: api-modelo-pod
  ports:
      # Escuta na porta 8080
    - port: 8081
      # Redireciona para a porta 8080
      targetPort: 8080
      # Escuta na porta 30000 fora do cluster
      nodePort: 30000