name: Docker

on: [workflow_call]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: luanpaivadev
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: luanpaivadev/api-modelo:latest
